@startuml RegularUpdate

skinparam componentStyle rectangle

title
UserDemand - Fault Management
end title

actor USER as USER

package "Regular Inventory Update" {
  interface GUI as GUI
  USER - GUI #Lightgrey

  component [Netcool\n] as Netcool
  GUI - Netcool #Lightgrey

  component [NetcoolProxy\n] as NCP
  Netcool --[hidden] NCP

  component [MicroWaveDeviceInventory\n] as MWDI
  NCP --[hidden] MWDI

  component [OpenDaylight\n] as ODL
  MWDI --[hidden] ODL

  component [Mediator\n] as Med
  ODL --[hidden] Med

  component [Device\n] as Dev
  Med --[hidden] Dev

  NCP --> Netcool #line:blue;text:blue : REST\nWebHook

  MWDI --> NCP #line:blue;text:blue : REST\nWebHook

  MWDI --> ODL : GET CC
  MWDI <.. ODL

  ODL --> Med
  ODL <.. Med

  Med --> Dev
  Med <.. Dev

}

@enduml